# Generated by Django 3.1.5 on 2022-02-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusarea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusarea',
            name='name',
        ),
        migrations.AddField(
            model_name='focusarea',
            name='title',
            field=models.CharField(blank=True, help_text="Focus Area's title", max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Focusarea_figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('Figure', models.IntegerField()),
                ('focusArea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='focusarea.focusarea')),
            ],
        ),
    ]
