# Generated by Django 3.1.5 on 2022-02-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusarea', '0002_auto_20220209_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='title',
            field=models.CharField(default='', help_text="Focus Area's title", max_length=40),
        ),
    ]
