# Generated by Django 3.1.5 on 2022-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Focus Area's name", max_length=40)),
                ('description', models.TextField(help_text='Description', max_length=1000)),
                ('focusArea_img', models.ImageField(upload_to='focus_area/')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.ImageField(upload_to='slides/')),
            ],
        ),
        migrations.DeleteModel(
            name='Slides',
        ),
    ]
