# Generated by Django 3.1.5 on 2022-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220208_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign Name', max_length=40)),
                ('description', models.TextField(help_text='Description', max_length=1000)),
                ('image', models.ImageField(upload_to='campaign/')),
            ],
        ),
    ]
