# Generated by Django 3.1.5 on 2022-02-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('focusarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign Name', max_length=40)),
                ('description', models.TextField(help_text='Description', max_length=1000)),
                ('image', models.ImageField(upload_to='campaign/')),
                ('Focusarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='focusarea.focusarea')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign_figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
