# Generated by Django 3.1.5 on 2022-02-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_figure',
            name='figure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign_figure',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, help_text='Campaign Name', max_length=40, null=True),
        ),
    ]
